
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowflake_dbt_poc'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

seeds:
    snowflake_dbt_poc:
        preqin:
            schema: dbt_trajan 

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    incremental_strategy: "merge"

    snowflake_dbt_poc:
        ############################################
        # Per current model we would materialise 
        # everything but presentation as table.
        ############################################
        # Applies to all files under models/example/
        #example:
        #    materialized: view
        # Applies to all files under models/l00_source/
        l00_source:
            materialized: view
        # Applies to all files under models/l10_staging/
        l10_staging:
            materialized: view
            stg_acumatica:
                schema: dbt_trajan
            stg_acv:
                schema: dbt_trajan    
            stg_preqin:
                materialized: ephemeral
            stg_salesforce:
                materialized: ephemeral
            stg_delighted:
                schema: dbt_trajan
        # Applies to all files under models/l120_marts/
        l20_marts:
            materialized: view
            acumatica:
                schema: dbt_trajan
            acv:
                schema: dbt_trajan    
            feedbackify:
                schema: dbt_trajan
            heap:
                schema: dbt_trajan
            preqin:
                schema: dbt_trajan
                +materialized: table
            presentation:
                schema: dbt_trajan
            salesforce:
                schema: dbt_trajan
            delighted:
                enabled: true
                schema: dbt_trajan
        # Applies to all files under models/l130_presentation/
            materialized: view
        heap_poc:
            fact:
                enabled: true
                schema: dbt_trajan
            dimension:
                enabled: true
                schema: dbt_trajan    
        presentation_poc:
            enabled: true
            schema: dbt_trajan

on-run-end:
    - "{{ grant_select_on_schemas(schemas, target.role) }}"
    - "{{ grant_select_on_schemas(schemas, 'MAMMOTH') }}"
