{% snapshot contacts_snapshot %}

    {{
        config(
          unique_key='ID',
          target_schema='hubspot_updates',          
          strategy='check',
          check_cols='all'
        )
    }}
    
SELECT 
    USER_ID AS ID,
    FIRST_NAME AS FIRSTNAME,
    LAST_NAME AS LASTNAME,
    COMPANY,
    INTEGRATION_SIGNUP,
    ARRAY_TO_STRING(INTEGRATION_ORDER, ';') as INTEGRATION_ORDER,
    DATE_PART('EPOCH_MILLISECOND', DATE_REGISTERED) as DATE_REGISTERED,
    EMAIL,
    DATE_PART('EPOCH_MILLISECOND', FIRST_ORDER_DATE) as FIRST_ORDER_DATE,
    DATE_PART('EPOCH_MILLISECOND', LAST_ORDER_DATE) as LAST_ORDER_DATE,
    TOTAL_ORDER_COUNT,
    LIFETIME_REVENUE,
    DATE_PART('EPOCH_MILLISECOND', THIRD_ORDER_DATE) as THIRD_ORDER_DATE,
    DATE_PART('EPOCH_MILLISECOND', PARTNER_RAMPED_DATE) as PARTNER_RAMPED_DATE,
    DAYS_BETWEEN_ORDERS1TO8,
    REVENUE_MTD,
    REVENUE_YTD,
    HAS_ISSUE_STATUS,
    CHURNED,
    DATE_PART('EPOCH_MILLISECOND', CHURN_DATE) as CHURN_DATE,
    PHONE,
    WEBSITE,
    EMAILS_PRODUCT_CATALOG,
    EMAILS_WEBINAR_EVENTS,
    EMAILS_NEW_FEATURES,
    THIRD_PARTY_APPS,
    RESEARCHED_WEBSITE_URL,
    FACEBOOK_FOLLOWERS,
    TWITTER_FOLLOWERS,
    PINTEREST_FOLLOWERS,
    INSTAGRAM_FOLLOWERS,
    ETSY_SALES,
    WEB_TRAFFIC,
    POTENTIAL_TIER,
    TOTAL_TICKETS,
    TICKETS_LAST30,
    OPEN_TICKETS
FROM {{ ref('silver_user_dimensions') }}
WHERE EMAIL IS NOT NULL

{% endsnapshot %}