{{ config(
    materialized = 'view',
    unique_key = 'DIMENSION_FIRM_KEY',
    tags = ["firm"]
) }}


SELECT F.DIMENSION_FIRM_KEY, TO_CHAR(F.FIRM_ID) AS FIRM_ID, F.FIRMNAME, F.DATASOURCE_ID, A.ACCOUNT_ID, A.CLASSIFICATION_C, A.REGION_C
FROM {{ ref('preqin_dimension_firm') }} F
--JOIN TO SALESFORCE ACCOUNT DIMENSION FOR SF MASTERED ATTRIBUTES
LEFT
JOIN {{ ref('salesforce_dimension_account') }} A
ON F.DIMENSION_FIRM_KEY = A.CONFORMED_DIMENSION_KEY

UNION 
SELECT A.DIMENSION_ACCOUNT_KEY, TO_CHAR(A.CRM_FIRM_ID_C), A.ACCOUNT_NAME, A.DATASOURCE_ID, A.ACCOUNT_ID, A.CLASSIFICATION_C, A.REGION_C
FROM {{ ref('salesforce_dimension_account') }} A
WHERE CONFORMED_DIMENSION_KEY IS NULL

UNION

SELECT F.DIMENSION_FIRM_KEY,TO_CHAR(F.LEGACY_FIRM_ID), F.FIRM_NAME, F.DATASOURCE_ID, F.ACCOUNT_ID, A.CLASSIFICATION_C, A.REGION_C
FROM {{ ref('heap_dimension_firm_integrated') }} F
--JOIN TO SALESFORCE ACCOUNT DIMENSION FOR SF MASTERED ATTRIBUTES
LEFT
JOIN {{ ref('salesforce_dimension_account') }}  A
ON F.SALESFORCE_DIMENSION_ACCOUNT_KEY = A.DIMENSION_ACCOUNT_KEY
WHERE F.CONFORMED_DIMENSION_KEY IS NULL