{{ config(
    materialized = 'view',
    unique_key = [],
    tags = []
) }}

SELECT '-1' AS DIMENSION_INDIVIDUAL_KEY, NULL AS CONTACTFIRM_ID, NULL CONTACT_TITLE, NULL CONTACT_FIRSTNAME, NULL AS CONTACT_LASTNAME, NULL AS EMAIL_ADDRESS, NULL AS LINKEDIN, FALSE AS IS_ACTIVE, '-1' AS DIMENSION_FIRM_KEY,  NULL AS DATASOURCE_ID
UNION
--1.Primary Contact list from Core
SELECT DIMENSION_INDIVIDUAL_KEY, CONTACTFIRM_ID, CONTACT_TITLE, CONTACT_FIRSTNAME, CONTACT_LASTNAME, EMAIL_ADDRESS, LINKEDIN, IS_ACTIVE, DIMENSION_FIRM_KEY, DATASOURCE_ID
FROM {{ ref('preqin_dimension_individual') }} I

--2 + any Unmapped Salesforce Contacts to Primary\Master Contact
UNION
SELECT DIMENSION_CONTACT_KEY, crm_contact_firm_id_c, TITLE, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, LINKEDIN, IS_ACTIVE, 
IFF(CONFORMED_DIMENSION_FIRM_KEY = '-1',DIMENSION_ACCOUNT_KEY, CONFORMED_DIMENSION_FIRM_KEY ) AS DIMENSION_FIRM_KEY,
DATASOURCE_ID
FROM {{ ref('salesforce_dimension_contact') }} C
WHERE 
    C.CONFORMED_DIMENSION_INDIVIDUAL_KEY ='-1'

--3 + any Unmapped Heap User to Primary\Master Contact
UNION
SELECT DIMENSION_USER_KEY, NULL CONTACTFIRM_ID, TITLE, FIRST_NAME, LAST_NAME, NULL, NULL, FALSE, 
IFF(CONFORMED_DIMENSION_FIRM_KEY = '-1',DIMENSION_FIRM_KEY, CONFORMED_DIMENSION_FIRM_KEY ) AS DIMENSION_FIRM_KEY,
DATASOURCE_ID
FROM {{ ref('heap_dimension_user_integrated') }} U
WHERE 
    U.CONFORMED_DIMENSION_INDIVIDUAL_KEY ='-1'
