
with date_spine as 
(
{{ dbt_utils.date_spine(
    datepart="day",
    start_date="'2018-01-01'",
    end_date="dateadd(month, 1, date_trunc('month', getdate()))"
   )
}}
)

SELECT
CAST(YEAR(CAST(DATE_DAY AS DATE)) || RIGHT('0' || MONTH(CAST(DATE_DAY AS DATE)), 2) || RIGHT('0' || DAYOFMONTH(CAST(DATE_DAY AS DATE)), 2) AS INT) AS DATE_KEY
,CAST(DATE_DAY AS DATE) AS DATE
,CAST(DAYOFYEAR(DATE) AS INT) AS DAY_OF_YEAR
,CAST(DECODE (RIGHT(EXTRACT(DAYOFMONTH FROM DATE), 1),
1 , 'st',
2 , 'nd',
3 , 'rd',
'th' 
) AS VARCHAR(2)) AS DAY_SUFFIX
,CAST(YEAR(DATE) || RIGHT('0' || WEEK(DATE), 2) AS INT) AS WEEK_KEY
,CAST(WEEKOFYEAR(DATE) AS INT) AS WEEK_OF_YEAR
,CAST(DAYOFWEEK(DATE) AS INT) AS DAY_OF_WEEK
,CAST(DAYNAME(DATE) AS VARCHAR(5)) AS WEEK_DAY_SHORT_DESC
,CAST(DECODE (EXTRACT(DAYOFWEEK FROM DATE),
0 , 'Sunday',
1 , 'Monday',
2 , 'Tuesday',
3 , 'Wednesday',
4 , 'Thursday',
5 , 'Friday',
6 , 'Saturday'
) AS VARCHAR(9)) AS WEEK_DAY_DESC
,CAST(TRUNC(DATE, 'Week') AS DATE) AS FIRST_DAY_OF_WEEK
,CAST(LAST_DAY(DATE, 'Week') AS DATE) AS LAST_DAY_OF_WEEK
,CAST(YEAR(DATE) || RIGHT('0' || MONTH(DATE), 2) AS INT) AS MONTH_KEY
,CAST(MONTH(DATE) AS INT) AS MONTH_OF_YEAR
,CAST(DAYOFMONTH(DATE) AS INT) AS DAY_OF_MONTH
,CAST(MONTHNAME(DATE) AS VARCHAR(5)) AS MONTH_SHORT_DESC
,CAST(TO_CHAR(DATE, 'MMMM') AS VARCHAR(50)) AS MONTH_DESC
,CAST(TRUNC(DATE, 'Month') AS DATE) AS FIRST_DAY_OF_MONTH
,CAST(LAST_DAY(DATE, 'Month') AS DATE) AS LAST_DAY_OF_MONTH
,CAST(YEAR(DATE) || QUARTER(DATE) AS INT) AS QUARTER_KEY
,CAST(QUARTER(DATE) AS INT) AS QUARTER_OF_YEAR
,CAST(DATE - TRUNC(DATE, 'Quarter') + 1 AS INT) AS DAY_OF_QUARTER
,CAST('Q' || QUARTER_OF_YEAR AS VARCHAR(5)) AS QUARTER_SHORT_DESC
,CAST('Quarter' || QUARTER_OF_YEAR AS VARCHAR(50)) AS QUARTER_DESC
,CAST(TRUNC(DATE, 'Quarter') AS DATE) AS FIRST_DAY_OF_QUARTER
,CAST(LAST_DAY(DATE, 'Quarter') AS DATE) AS LAST_DAY_OF_QUARTER
,CAST(YEAR(DATE) AS INT) AS YEAR_KEY
,CAST(TRUNC(DATE, 'Year') AS DATE) AS FIRST_DAY_OF_YEAR
,CAST(LAST_DAY(DATE, 'Year') AS DATE) AS LAST_DAY_OF_YEAR
,IFF(DAY_OF_WEEK = 6 or DAY_OF_WEEK=0, FALSE, TRUE ) IS_WEEK_DAY
,IFF(DATE = CAST(GETDATE() AS DATE), TRUE, FALSE ) IS_TODAY
,IFF(DATE = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE), TRUE, FALSE ) IS_YESTERDAY
,IFF(DATE = CAST(DATEADD(DAY, 1, GETDATE()) AS DATE), TRUE, FALSE ) IS_TOMORROW
,IFF(YEAR_KEY = CAST(YEAR(GETDATE()) AS INT), TRUE, FALSE) IS_CURRENT_YEAR
,IFF(YEAR_KEY = CAST(YEAR(DATEADD(YEAR,-1,GETDATE())) AS INT), TRUE, FALSE) IS_PREVIOUS_YEAR
,IFF(YEAR_KEY = CAST(YEAR(DATEADD(YEAR,1,GETDATE())) AS INT), TRUE, FALSE) IS_NEXT_YEAR
,IFF(DATE >= CAST(TRUNC(GETDATE(), 'Month') AS DATE) AND  DATE<=GETDATE(),TRUE, FALSE) IS_MONTH_TO_DATE
,IFF(DATE >= CAST(TRUNC(GETDATE(), 'Quarter') AS DATE) AND  DATE<=GETDATE(),TRUE, FALSE) IS_QUARTER_TO_DATE
,IFF(DATE >= CAST(TRUNC(GETDATE(), 'Year') AS DATE) AND  DATE<=GETDATE(),TRUE, FALSE) IS_YEAR_TO_DATE
,IFF(MONTH_KEY = CAST(YEAR(GETDATE()) || RIGHT('0' || MONTH(GETDATE()), 2) AS INT), TRUE, FALSE) IS_CURRENT_MONTH
,IFF(MONTH_KEY = CAST(YEAR(DATEADD(MONTH,-1,GETDATE())) || RIGHT('0' || MONTH(DATEADD(MONTH,-1,GETDATE())), 2) AS INT), TRUE, FALSE) IS_PREVIOUS_MONTH
,IFF(MONTH_KEY = CAST(YEAR(DATEADD(MONTH,1,GETDATE())) || RIGHT('0' || MONTH(DATEADD(MONTH,1,GETDATE())), 2) AS INT), TRUE, FALSE) IS_NEXT_MONTH
,IFF(QUARTER_KEY = CAST(YEAR(GETDATE()) || QUARTER(GETDATE()) AS INT), TRUE, FALSE) IS_CURRENT_QUARTER
,IFF(QUARTER_KEY = CAST(YEAR(DATEADD(QUARTER, -1, GETDATE())) || QUARTER(DATEADD(QUARTER, -1, GETDATE())) AS INT), TRUE, FALSE) IS_PREVIOUS_QUARTER
,IFF(QUARTER_KEY = CAST(YEAR(DATEADD(QUARTER, 1, GETDATE())) || QUARTER(DATEADD(QUARTER, 1, GETDATE())) AS INT), TRUE, FALSE) IS_NEXT_QUARTER
,IFF(DATE >= DATEADD(DAY, -30, GETDATE()) AND  DATE<=GETDATE(),TRUE, FALSE) IS_ROLLING_30_DAYS
,IFF(DATE >= DATEADD(YEAR, -1, GETDATE()) AND  DATE<=GETDATE(),TRUE, FALSE) IS_ROLLING_YEAR
,IFF(DATE = CAST(LAST_DAY(DATE, 'Month') AS DATE) OR IS_TODAY = TRUE, TRUE, FALSE)  IS_LAST_DAY_OF_MONTH
FROM DATE_SPINE
