SELECT '-1' AS DIMENSION_FIRM_ADDRESS_KEY, NULL AS FIRM_ADDRESS_ID,  NULL AS ADDRESS_LINE_1, NULL AS ADDRESS_LINE_2, NULL AS CITY, NULL AS STATE, NULL AS POSTAL_CODE, NULL AS COUNTRY
UNION
SELECT 
DIMENSION_FIRM_ADDRESS_KEY,
FIRM_ADDRESS_ID,
ADDRESS_LINE_1,
ADDRESS_LINE_2,
CITY,
STATE,
POSTAL_CODE,
COUNTRY
FROM {{ ref('preqin_dimension_firm_address') }} fa