{{ config(
    materialized = 'view',
    unique_key = [],
    tags = []
) }}

SELECT 
(F.DATE::DATE) AS DATE_KEY,
COALESCE(Firm.CONFORMED_DIMENSION_KEY, Firm.DIMENSION_FIRM_KEY, TO_CHAR(-1)) AS DIMENSION_FIRM_KEY,
PAGEVIEWS,
SESSIONS,
DESKTOP_SESSIONS,
MOBILE_SESSIONS,
TABLET_SESSIONS,
CREATE_ADD_TARGET_LIST,
CREATE_ADD_CUSTOM_BENCHMARK,
SAVE_NEW_SEARCH,
CREATE_ALERT,
TOTAL_DOWNLOADS,
SEARCH_DOWNLOADS,
PROFILE_DOWNLOADS,
CHART_DOWNLOADS,
MARKET_BENCHMARK_DOWNLOADS,
TARGET_LIST_DOWNLOADS,
MY_BENCHMARK_DOWNLOADS
FROM {{ ref('presentation_heap_daily_user_summary') }} F
LEFT
JOIN {{ ref('heap_dimension_firm_integrated') }} Firm
    ON F.Account_ID = Firm.Account_ID