version: 2
sources:
  
  - name: heap
    database: DB_DATAEXCHANGE_HEAP
    schema: HEAP
    loader: heap
    tables:
      - name: _SYNC_INFO
        loaded_at_field: SYNCED_TO_TIME
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: users
      - name: sessions
      - name: all_events
      - name: pageviews
      - name: mammoth_poc_reports_insights_insights_page_viewed
      - name: mammoth_poc_reports_pro_key_actions_app_page_viewed
      - name: mammoth_poc_reports_pro_key_actions_data_table_download_confirmed

  - name: preqin
    database: DB_RAW
    schema: PREQIN01_PROD_RIVERY
    loader: rivery
    tables:
      - name: tblFirm
      - name: tblParentFirm
      - name: tblFirm_Type
      - name: tblFirm_Address
      - name: STG_Data_Delivery_Data_Feeds_PageLogs
      - name: tblContactFirm
      - name: tblContact
      - name: tblpei_product
      - name: tbluser_details
      - name: tbluser_Subscription

  - name: salesforce
    database: DB_RAW
    schema: SALESFORCE_RIVERY
    loader: rivery
    tables:
      - name: account
      - name: user
      - name: contact
      - name: contact_test
 
  - name: acumatica
    database: DB_RAW
    schema: ALTERYX_FINANCE
    loader: alteryx
    tables:
      - name: book_of_business

  - name: feedbackify
    database: DB_RAW
    schema: ALTERYX_FINANCE
    loader: alteryx
    tables:
      - name: net_promoter_score
