version: 2
sources:
  
  - name: heap
    description: Heap is a product analytics platform that Preqin uses to provide a complete dataset 
                of user behavior.
    database: DB_DATAEXCHANGE_HEAP
    schema: HEAP
    loader: heap
    tables:
      - name: _SYNC_INFO
        loaded_at_field: SYNCED_TO_TIME
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: users
      - name: sessions
      - name: all_events
      - name: pageviews
      - name: mammoth_poc_reports_insights_insights_page_viewed
      - name: mammoth_poc_reports_pro_key_actions_app_page_viewed
      - name: mammoth_poc_reports_pro_key_actions_data_table_download_confirmed

  - name: preqin
    description: Preqin CRM platform, also referred to as the server it runs on Preqin01.
    database: DB_RAW
    schema: PREQIN01_PROD_RIVERY
    loader: rivery
    tables:
      - name: tblFirm
      - name: tblParentFirm
      - name: tblFirm_Type
      - name: tblFirm_Address
      - name: STG_Data_Delivery_Data_Feeds_PageLogs
      - name: tblContactFirm
      - name: tblContact

  - name: salesforce
    description: Salesforce CRM platform.
    database: DB_RAW
    schema: SALESFORCE_RIVERY
    loader: rivery
    tables:
      - name: account
      - name: user
      - name: contact
      - name: contact_test
 
  - name: acumatica
    description: ERP system. Source of Book of Business etc..
    database: DB_RAW
    schema: ALTERYX_FINANCE
    loader: alteryx
    tables:
      - name: book_of_business
        description: Loaded into Snowflake manually monthly from an Alteryx workflow that 
                    uses Book of Business data from Acumatica with manual adjustments by 
                    Finance / Revops.

  - name: feedbackify
    description: Website feedback solution used by Preqin to gather NPS (Net Promoter Score).
    database: DB_RAW
    schema: ALTERYX_FINANCE
    loader: alteryx
    tables:
      - name: net_promoter_score
        description: Loaded into Snowflake manually monthly from an Alteryx workflow that 
                    connects to Feedbackify to get a csv export of all NPS.
